---
- hosts: 172.31.14.190
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: I want to copy mytestfile into the node side
    copy:
      src: mytestfile
      dest: /home/ubuntu/mytestfile

  - name: I want to copy index.j2 file into node side
    template:
      src: myindex.j2
      dest: /var/www/html/index.html  