---
- hosts: 172.31.14.190
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: I want to copy mytestfile into the node side
    copy:
      src: mytestfile
      dest: /home/ubuntu/mytestfile

  - name: I want to copy index.j2 file into node side
    template:
      src: myindex.j2
      dest: /var/www/html/index.html  
    notify: restartwebserver
  
  - name: I want to download internet file
    get_url:
      url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz
      dest: /home/ubuntu/apache-tomcat-10.0.20.tar.gz
      force_basic_auth: yes
      
  handlers:
  - name: restartwebserver
    service: